name: Swift with CocoaPods

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods

    - name: Install project dependencies
      run: |
        pod install --repo-update

    - name: Cache CocoaPods dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cocoapods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-cocoapods-

    - name: Xcode build
      run: xcodebuild -scheme "Rabble Hub" -workspace "Rabble Hub.xcworkspace" -configuration Release -allowProvisioningUpdates -provisioningProfile "5812fc49-b5df-4cf6-84f5-9bf4dbf63442" build
