name: Swift with CocoaPods

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Update to the latest version

    # Install CocoaPods
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods

    # Install project dependencies using CocoaPods
    - name: Install project dependencies
      run: |
        pod install --repo-update

    # Cache CocoaPods dependencies
    - name: Cache CocoaPods dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cocoapods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-cocoapods-

    # Xcode build
    - name: Xcode build
      run: xcodebuild -scheme "Rabble Hub" -workspace "Rabble Hub.xcworkspace" build
