name: Swift Build

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build:
    name: Swift ${{ matrix.swift }} on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ["5.2", "5.3"]
    steps:
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: swift build
